# Generated by Django 3.0.3 on 2020-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
